In [1]:
import matplotlib.pyplot as plt
from matplotlib import animation
from random import choice, random, randint
from math import exp, sqrt, log, sinh
import numpy as np
import sys
import time

In [2]:
N_VALUES = [10, 50, 100] # Values for N
N_WAIT_VALUES = [100, 1000] # Steps to let the system ''relax'' to the important states
N_SAMPLES_VALUES = [1000, 10000]

In [3]:
T = np.linspace(0.2,4.0,20,endpoint=True)

Tc = float(2/log(1 + sqrt(2)))

plot_dic = {}


In [391]:
def change_energy(row, column,system):
    rows,columns = system.shape
    energy = system[row][column]*(system[(row+1)%rows][column]+system[row][(column+1)%columns]+system[(row-1)%rows][column]+system[row][(column-1)%columns])*2
    return energy

def myenergy(system):
    rows, columns = system.shape
    E = 0.
    count = np.array([[0]*rows]*columns)
    for i in range(rows):
        for j in range(columns):
            
            aux = -system[i][j]*(system[(i+1)%rows][j]+system[i][(j+1)%columns]+system[(i-1)%rows][j]+system[i][(j-1)%columns])/2

            E += aux
            count[i,j] = aux
           
            #print i,j, E
    return E,count
    
    

In [6]:
def calculate_variation_of_energy(row,column,N):
    return -4*check_energy(row,column,N)

In [169]:
N = N_VALUES[0]

In [8]:
i, wait = enumerate(N_WAIT_VALUES)

In [9]:
E = {} # energy
E_2 = {} # energy squared
magnetization = {}
magnetization_2 = {}
C = {} #specifid heat
infinite_magnetization={} #infinte magnetization

In [10]:
Ti = T[0]

In [237]:
system = []
for i in range(N):
    system.append([])
    for j in range(N):
        system[-1].append(choice([-1,1]))
system = np.array(system)

In [238]:
print system.shape

(10, 10)


In [13]:
probability = {}
energies = np.array([-8, -4, -2, 0, 2, 4, 8])
k_b = 1
for energy in energies:
    probability[energy] = exp(-energy/float(Ti))

In [14]:
print probability

{0: 1.0, 2: 4.5399929762484854e-05, 4: 2.061153622438558e-09, 8: 4.248354255291589e-18, -8: 2.3538526683702e+17, -4: 485165195.4097903, -2: 22026.465794806718}


In [239]:
system_energy = np.array([[0.]*N]*N,dtype='float')
total_energy = 0
total_magnetization = 0
for i in xrange(1,N-1):
    for j in xrange(1,N-1):
        auxE = check_energy(i, j,N)
        total_energy += auxE
        total_magnetization += system[i][j]
        system_energy[i,j] = auxE


In [245]:
print total_energy , '  ' , total_magnetization , '\n' , system,'\n', system_energy

17    -4 
[[ 1 -1  1  1 -1  1 -1 -1 -1  1]
 [-1  1 -1  1 -1 -1  1 -1  1  1]
 [-1  1  1 -1 -1  1 -1  1  1 -1]
 [ 1  1 -1  1  1 -1  1 -1 -1  1]
 [-1 -1  1 -1  1 -1 -1 -1 -1 -1]
 [ 1  1  1 -1  1 -1 -1 -1 -1 -1]
 [-1  1  1  1 -1 -1  1 -1  1  1]
 [ 1 -1 -1  1  1  1 -1 -1  1  1]
 [-1 -1 -1  1 -1  1 -1  1 -1  1]
 [ 1 -1  1 -1 -1 -1  1  1  1  1]] 
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  1. -1.  1.  2.  1.  0.  0.]
 [ 0. -1.  1.  1.  0.  2.  2.  1.  0.  0.]
 [ 0.  0.  2.  1.  0.  1.  2.  0.  0.  0.]
 [ 0.  1.  1.  1.  0. -1. -1. -2. -2.  0.]
 [ 0. -1. -1.  1.  1. -1. -1. -2. -1.  0.]
 [ 0.  0. -1.  0.  1.  0.  2.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0. -2.  0.  1.  1.  1.  1.  1.  2.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [241]:
system_energy[0,0],check_energy(5,5,N)

(0.0, -1)

In [252]:
 myenergy(system)

(24.0, array([[ 0,  1,  0,  0,  0,  2,  1, -1,  1, -1],
        [ 1,  1,  2,  1, -1,  1,  2,  1,  0,  0],
        [ 0, -1,  1,  1,  0,  2,  2,  1,  0,  1],
        [ 0,  0,  2,  1,  0,  1,  2,  0,  0,  1],
        [ 0,  1,  1,  1,  0, -1, -1, -2, -2, -1],
        [ 1, -1, -1,  1,  1, -1, -1, -2, -1,  0],
        [ 2,  0, -1,  0,  1,  0,  2,  0,  0,  0],
        [ 1,  0,  0, -1,  0,  0,  0,  0,  0, -2],
        [ 1, -2,  0,  1,  1,  1,  1,  1,  2,  0],
        [ 0,  0,  1,  1, -2,  1,  1, -1,  0, -2]]))

In [21]:
system= np.array([[1,-1,1,-1,1,-1],[-1,1,-1,1,-1,1],[1,-1,1,-1,1,-1],[-1,1,-1,1,-1,1],[1,-1,1,-1,1,-1],[-1,1,-1,1,-1,1]])


In [136]:
wait = 100

In [412]:
#for step in np.arange(wait):
auxsystem = np.copy(system)
column=randint(0,N-1)
row=randint(0,N-1)
auxsystem[row,column] *= -1
deltaE = myenergy(auxsystem)[0]-myenergy(system)[0]
a = change_energy(row,column,system)
print deltaE,a

#if deltaE>0:
#   if exp(deltaE/Ti)<random():
#      system = np.copy(auxsystem)

-8.0 -8


In [390]:
a = change_energy(row,column,system)
if not abs(deltaE) == abs(a):
    print row,column
    print system[row-1:row+2,column-1:column+2]
    print auxsystem[row-1:row+2,column-1:column+2]

1 3
[[ 1  1 -1]
 [-1  1 -1]
 [ 1 -1 -1]]
[[ 1  1 -1]
 [-1 -1 -1]
 [ 1 -1 -1]]


In [348]:
c  = system==auxsystem

In [211]:
mac,mbc = myenergy(system[row-1:row+2,column-1:column+2])
ma,mb = myenergy(system)

In [212]:
asd,asdd = myenergy(auxsystem[row-1:row+2,column-1:column+2])
aa,ab = myenergy(auxsystem)

In [232]:
auxsystem[row,column] = 5
print auxsystem[row-2:row+3,column-1:column+3]

print mb[row-2:row+3,column-1:column+3]
print ab[row-2:row+3,column-1:column+3]
print ab[row-2:row+3,column-1:column+3]==mb[row-2:row+3,column-2:column+3]

[[ 1  1 -1 -1]
 [ 1  1  1 -1]
 [ 1  5 -1  1]
 [-1 -1  1 -1]
 [-1  1  1 -1]]
[[ 0 -1  1  0]
 [ 0 -1  1  1]
 [ 0  0  1  1]
 [ 0  0  1  0]
 [ 0  1 -1  1]]
[[ 0 -1  1  0]
 [ 0 -2  1  1]
 [ 0  0  2  1]
 [ 0  1  1  0]
 [ 0  1 -1  1]]
False


/home/brais/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:6: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
